# Generated by Django 4.0 on 2022-01-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSiteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name_en', models.CharField(max_length=500)),
                ('display_name_fr', models.CharField(max_length=500)),
                ('description_en', models.CharField(max_length=5000)),
                ('description_fr', models.CharField(max_length=5000)),
                ('ait_collection_map', models.JSONField(default=list)),
            ],
        ),
    ]
